# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/smorod1na/kursovaia_Sinelnikov

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/smorod1na/kursovaia_Sinelnikov

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/smorod1na/kursovaia_Sinelnikov/CMakeFiles /home/smorod1na/kursovaia_Sinelnikov//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/smorod1na/kursovaia_Sinelnikov/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tttcore

# Build rule for target.
tttcore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tttcore
.PHONY : tttcore

# fast build rule for target.
tttcore/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/build
.PHONY : tttcore/fast

#=============================================================================
# Target rules for targets named tttplayer

# Build rule for target.
tttplayer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tttplayer
.PHONY : tttplayer

# fast build rule for target.
tttplayer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttplayer.dir/build.make CMakeFiles/tttplayer.dir/build
.PHONY : tttplayer/fast

#=============================================================================
# Target rules for targets named test_my_player

# Build rule for target.
test_my_player: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_my_player
.PHONY : test_my_player

# fast build rule for target.
test_my_player/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_my_player.dir/build.make tests/CMakeFiles/test_my_player.dir/build
.PHONY : test_my_player/fast

#=============================================================================
# Target rules for targets named test_stats

# Build rule for target.
test_stats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_stats
.PHONY : test_stats

# fast build rule for target.
test_stats/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_stats.dir/build.make tests/CMakeFiles/test_stats.dir/build
.PHONY : test_stats/fast

#=============================================================================
# Target rules for targets named test_my_player_unit

# Build rule for target.
test_my_player_unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_my_player_unit
.PHONY : test_my_player_unit

# fast build rule for target.
test_my_player_unit/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_my_player_unit.dir/build.make tests/CMakeFiles/test_my_player_unit.dir/build
.PHONY : test_my_player_unit/fast

src/core/event.o: src/core/event.cpp.o
.PHONY : src/core/event.o

# target to build an object file
src/core/event.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/event.cpp.o
.PHONY : src/core/event.cpp.o

src/core/event.i: src/core/event.cpp.i
.PHONY : src/core/event.i

# target to preprocess a source file
src/core/event.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/event.cpp.i
.PHONY : src/core/event.cpp.i

src/core/event.s: src/core/event.cpp.s
.PHONY : src/core/event.s

# target to generate assembly for a file
src/core/event.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/event.cpp.s
.PHONY : src/core/event.cpp.s

src/core/field.o: src/core/field.cpp.o
.PHONY : src/core/field.o

# target to build an object file
src/core/field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/field.cpp.o
.PHONY : src/core/field.cpp.o

src/core/field.i: src/core/field.cpp.i
.PHONY : src/core/field.i

# target to preprocess a source file
src/core/field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/field.cpp.i
.PHONY : src/core/field.cpp.i

src/core/field.s: src/core/field.cpp.s
.PHONY : src/core/field.s

# target to generate assembly for a file
src/core/field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/field.cpp.s
.PHONY : src/core/field.cpp.s

src/core/game.o: src/core/game.cpp.o
.PHONY : src/core/game.o

# target to build an object file
src/core/game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/game.cpp.o
.PHONY : src/core/game.cpp.o

src/core/game.i: src/core/game.cpp.i
.PHONY : src/core/game.i

# target to preprocess a source file
src/core/game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/game.cpp.i
.PHONY : src/core/game.cpp.i

src/core/game.s: src/core/game.cpp.s
.PHONY : src/core/game.s

# target to generate assembly for a file
src/core/game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/game.cpp.s
.PHONY : src/core/game.cpp.s

src/core/state.o: src/core/state.cpp.o
.PHONY : src/core/state.o

# target to build an object file
src/core/state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/state.cpp.o
.PHONY : src/core/state.cpp.o

src/core/state.i: src/core/state.cpp.i
.PHONY : src/core/state.i

# target to preprocess a source file
src/core/state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/state.cpp.i
.PHONY : src/core/state.cpp.i

src/core/state.s: src/core/state.cpp.s
.PHONY : src/core/state.s

# target to generate assembly for a file
src/core/state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttcore.dir/build.make CMakeFiles/tttcore.dir/src/core/state.cpp.s
.PHONY : src/core/state.cpp.s

src/player/my_observer.o: src/player/my_observer.cpp.o
.PHONY : src/player/my_observer.o

# target to build an object file
src/player/my_observer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttplayer.dir/build.make CMakeFiles/tttplayer.dir/src/player/my_observer.cpp.o
.PHONY : src/player/my_observer.cpp.o

src/player/my_observer.i: src/player/my_observer.cpp.i
.PHONY : src/player/my_observer.i

# target to preprocess a source file
src/player/my_observer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttplayer.dir/build.make CMakeFiles/tttplayer.dir/src/player/my_observer.cpp.i
.PHONY : src/player/my_observer.cpp.i

src/player/my_observer.s: src/player/my_observer.cpp.s
.PHONY : src/player/my_observer.s

# target to generate assembly for a file
src/player/my_observer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttplayer.dir/build.make CMakeFiles/tttplayer.dir/src/player/my_observer.cpp.s
.PHONY : src/player/my_observer.cpp.s

src/player/my_player.o: src/player/my_player.cpp.o
.PHONY : src/player/my_player.o

# target to build an object file
src/player/my_player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttplayer.dir/build.make CMakeFiles/tttplayer.dir/src/player/my_player.cpp.o
.PHONY : src/player/my_player.cpp.o

src/player/my_player.i: src/player/my_player.cpp.i
.PHONY : src/player/my_player.i

# target to preprocess a source file
src/player/my_player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttplayer.dir/build.make CMakeFiles/tttplayer.dir/src/player/my_player.cpp.i
.PHONY : src/player/my_player.cpp.i

src/player/my_player.s: src/player/my_player.cpp.s
.PHONY : src/player/my_player.s

# target to generate assembly for a file
src/player/my_player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tttplayer.dir/build.make CMakeFiles/tttplayer.dir/src/player/my_player.cpp.s
.PHONY : src/player/my_player.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... test_my_player"
	@echo "... test_my_player_unit"
	@echo "... test_stats"
	@echo "... tttcore"
	@echo "... tttplayer"
	@echo "... src/core/event.o"
	@echo "... src/core/event.i"
	@echo "... src/core/event.s"
	@echo "... src/core/field.o"
	@echo "... src/core/field.i"
	@echo "... src/core/field.s"
	@echo "... src/core/game.o"
	@echo "... src/core/game.i"
	@echo "... src/core/game.s"
	@echo "... src/core/state.o"
	@echo "... src/core/state.i"
	@echo "... src/core/state.s"
	@echo "... src/player/my_observer.o"
	@echo "... src/player/my_observer.i"
	@echo "... src/player/my_observer.s"
	@echo "... src/player/my_player.o"
	@echo "... src/player/my_player.i"
	@echo "... src/player/my_player.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

